config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      namespace :active_storage do
        resources :variant_records
      end
      namespace :active_storage do
        resources :attachments
      end
      resources :announcements
      resources :notifications
      namespace :active_storage do
        resources :blobs
      end
      resources :services
      resources :users
      resources :businesses
      root to: 'dashboard#show'
    end
  end

  resources :businesses, only: [:index] do
    resources :slots
  end

  authenticate :user, ->(u) { u.owner? } do
    resources :businesses
  end

  resources :notifications, only: %i[index show]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
# frozen_string_literal: true

class BusinessesController < ApplicationController
  before_action :set_business, only: %i[show edit update destroy]

  # GET /businesses or /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1 or /businesses/1.json
  def show; end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit; end

  # POST /businesses or /businesses.json
  def create
    @business = Business.new(business_params)
    @business.user = current_user

    respond_to do |format|
      if @business.save
        BusinessNotification.with(business: @business, method: :create).deliver_later(current_user)
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1 or /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1 or /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_business
    @business = Business.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def business_params
    params.require(:business).permit(:name, :description, :logo, address: %i[street city state zipcode])
  end
end

app/controllers/madmin/businesses_controller.rb
# frozen_string_literal: true

module Madmin
  class BusinessesController < Madmin::ResourceController
  end
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

module BusinessesHelper
end

app/views/businesses/_business.html.erb
<%= content_tag :tr, id: dom_id(business), class: dom_class(business) do %>
  <td>
    <%= link_to business.name, business %>
  </td>
  <td>
    <%= business.description %>
  </td>
<% end %>

app/views/businesses/_form.html.erb
<%= form_with(model: business) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>
      <ul>
        <% business.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control',placeholder: "My Business Name" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control',placeholder: "My Business provides..." %>
  </div>
  <h4> Address </h4>
  <%= form.fields_for :address, OpenStruct.new(form.object.address || {}) do |address| %>
    <div class="form-group">
      <%= form.label :street %>
      <%= address.text_field :street,class: 'form-control', placeholder: "123 Road St" %>
    </div>
    <div class="form-group">
      <%= form.label :city %>
      <%= address.text_field :city,class: 'form-control', placeholder: "Kansas City" %>
    </div>
    <div class="form-group">
      <%= form.label :state %>
      <%= address.text_field :state,class: 'form-control', placeholder: "KS"  %>
    </div>
    <div class="form-group">
      <%= form.label :zipcode %>
      <%= address.text_field :zipcode,class: 'form-control', pattern: '[0-9]{5}', placeholder: "12345" %>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :logo %>
    <%= form.file_field :logo, accept:'image/*' %>
  </div>
  <%= image_tag logo_path(form.object), class: "rounded border shadow-sm d-block mx-auto my-3" %>
  <div class="form-group">
    <% if business.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', business, method: :delete, class: "text-danger", data: { confirm: "This will permanently delete this business and all it's associations." } %>
      </div>
    <% end %>
    <%= form.submit class: 'btn btn-primary' %>
    <% if business.persisted? %>
      <%= link_to "Cancel", business, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Cancel", businesses_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>

<%= render 'form', business: @business %>

app/views/businesses/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Businesses</h1>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to new_business_path, class: 'btn btn-primary' do %>
      Add New Business
    <% end %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <%= render @businesses %>
    </tbody>
  </table>
</div>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form', business: @business %>

app/views/businesses/show.html.erb
<div class="page-header">
  <%= link_to businesses_path, class: 'btn btn-primary' do %>
    All Businesses
  <% end %>
  <%= link_to edit_business_path(@business), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show business</h1>
</div>
<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @business.name %></dd>
  <dt>Description:</dt>
  <dd><%= @business.description %></dd>
  <h4>Address</h4>
  <dt>Street:</dt>
  <dd><%= @business.address[:street] %></dd>
  <dt>City:</dt>
  <dd><%= @business.address[:city] %></dd>
  <dt>State:</dt>
  <dd><%= @business.address[:state] %></dd>
  <dt>Zipcode:</dt>
  <dd><%= @business.address[:zipcode] %></dd>
  <dt>Logo:</dt>
  <dd><%= image_tag logo_path(@business), class: "rounded border shadow-sm d-block mx-auto my-3" %></dd>
</dl>