config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      namespace :active_storage do
        resources :variant_records
      end
      namespace :active_storage do
        resources :attachments
      end
      resources :announcements
      resources :notifications
      namespace :active_storage do
        resources :blobs
      end
      resources :services
      resources :users
      resources :businesses
      root to: 'dashboard#show'
    end
  end

  resources :businesses, only: [:index] do
    resources :slots
  end

  authenticate :user, ->(u) { u.owner? } do
    resources :businesses
  end

  resources :notifications, only: %i[index show]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/slot.rb
# frozen_string_literal: true

class Slot < ApplicationRecord
  belongs_to :business

  validates :starts_at, :ends_at, presence: true
  validate :starts_at_is_before_ends_at

  private

  def starts_at_is_before_ends_at
    errors.add(:base, "starts at must be before ends at") unless starts_at.before?(ends_at)
  end
end

app/controllers/slots_controller.rb
# frozen_string_literal: true

class SlotsController < ApplicationController
  before_action :set_business
  before_action :set_slot, only: %i[show edit update destroy]

  # GET /slots or /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1 or /slots/1.json
  def show; end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit; end

  # POST /slots or /slots.json
  def create
    @slot = Slot.new(slot_params)
    @slot.business = @business

    respond_to do |format|
      if @slot.save
        format.html { redirect_to [@business, @slot], notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1 or /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1 or /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_slot
    @slot = Slot.find(params[:id])
  end

  def set_business
    @business = Business.find(params[:business_id])
  end

  # Only allow a list of trusted parameters through.
  def slot_params
    params.require(:slot).permit(:starts_at, :ends_at, :note, :business_id, :max_capacity)
  end
end

app/helpers/slots_helper.rb
# frozen_string_literal: true

module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_with(model: [@business, slot]) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>
      <ul>
        <% slot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at, class: 'form-control', ampm: true, prompt: true %>
  </div>
  <div class="form-group">
    <%= form.label :ends_at %>
    <%= form.datetime_select :ends_at, class: 'form-control', ampm: true, prompt: true %>
  </div>
  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :max_capacity %>
    <%= form.number_field :max_capacity, class: 'form-control' %>
  </div>
  <div class="form-group">
    <% if slot.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', [@business, slot], method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <%= form.submit class: 'btn btn-primary' %>
    <% if slot.persisted? %>
      <%= link_to "Cancel", [@business, slot], class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Cancel", business_slots_path(@business), class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Edit Slot</h1>

<%= render 'form', slot: @slot %>

app/views/slots/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Slots</h1>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to new_business_slot_path(@business), class: 'btn btn-primary' do %>
      Add New Slot
    <% end %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Starts at</th>
        <th>Ends at</th>
        <th>Note</th>
        <th>Max capacity</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @slots.each do |slot| %>
        <%= content_tag :tr, id: dom_id(slot), class: dom_class(slot) do %>
          <td><%= slot.starts_at %></td>
          <td><%= slot.ends_at %></td>
          <td><%= slot.note %></td>
          <td><%= slot.max_capacity %></td>
          <td><%= link_to 'Show', [@business, slot] %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/slots/new.html.erb
<h1>New slot</h1>

<%= render 'form', slot: @slot %>

app/views/slots/show.html.erb
<div class="page-header">
  <%= link_to business_slots_path(@business), class: 'btn btn-default' do %>
    All Slots
  <% end %>
  <%= link_to edit_business_slot_path(@business, @slot), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show slot</h1>
</div>

<dl class="dl-horizontal">
  <dt>Starts at:</dt>
  <dd><%= @slot.starts_at %></dd>

  <dt>Ends at:</dt>
  <dd><%= @slot.ends_at %></dd>

  <dt>Note:</dt>
  <dd><%= @slot.note %></dd>

  <dt>Business:</dt>
  <dd><%= @slot.business.name %></dd>

  <dt>Max capacity:</dt>
  <dd><%= @slot.max_capacity %></dd>

</dl>